### DISCUSSION TITLE
Smart Plugs - Power Mode Selector Conflict

### DISCUSSION THREAD

**Discussion by Roving-Ronin** [athom-tech/athom-configs#87] [General]
@athom-tech @tarontop 

Aiden,

Just looking at the power_mode selector option that was added to the plugs and reviewing against prior code. 
I note that this code;

```
switch:
  - platform: gpio
    name: "Switch"
    pin: GPIO12
    id: relay
    restore_mode: ${relay_restore_mode}
```

 that calls the subsitute:
```
 relay_restore_mode: RESTORE_DEFAULT_ON
```
Is still in the yaml. Wouldn't this code conflict (or at least see two different settings trying to do the same thing) with:

```
esphome:
  on_boot:
    - priority: 600
      then:
        - select.set_index:
            id: power_mode
            index: !lambda |-
                    return id(restore_mode)-1;
        - lambda: |-
              switch(id(restore_mode))
              {
              case 1:{
                      id(relay).turn_off();
                      break;
                            }
              case 2:{
                      id(relay).turn_on();
                      break;
                            }
              default:{
                      break;
                            }
              }

select:
  - platform: template
    name: "Power On State"
    id: "power_mode"
    optimistic: true
    options:
      - Always Off
      - Always On
      - Restore Power Off State
    on_value:
      then:
        - lambda: |-
            id(restore_mode)=i+1;
```

???

**Comment by Roving-Ronin** [comment]
@tarontop 
Suggest the substitution be changed to 'RESTORE_DEFAULT_ON' that will allow the on_boot logic to decide the final state.

**Comment by Roving-Ronin** [comment]
Does anyone else have this working? Even when changing this to default state = 2 (Always On), I find that after factory resetting a plug, that it continues to come back as 'Default OFF' ?

Seems to be that only the first option is being read from the code. Just found that whilst changing option to '2' doesn't work (as it should do), that swapping around the options in the yaml, so ALWAYS_ON is first, does work.

```
esphome:
  on_boot:
    - priority: 600
      then:
        - select.set_index:
            id: power_mode
            index: !lambda |-
                    return id(restore_mode)-1;
        - lambda: |-
              switch(id(restore_mode))
              {
              case 1:{
                      id(relay).turn_on();
                      break;
                            }
              case 2:{
                      id(relay).turn_off();
                      break;
                            }
              default:{
                      break;
                            }
              }


globals:
  - id: restore_mode
    type: int
    restore_value: yes
    initial_value: "1"    # Default to "Always On"


switch:
  - platform: gpio
    name: "GPO Switch"
    pin: ${gpo_switch_pin}
    id: relay
    restore_mode: ${relay_restore_mode}
    icon: "mdi:power-socket-au"
    web_server_sorting_weight: 12
```

${relay_restore_mode} maps to 'RESTORE_DEFAULT_ON' that should allow this logic to apply over the top of it (whilst ALWAYS_ON / ALWAYS_OFF when used there, would take precedence and cause this on_boot / selector to not work.

**Comment by Lordfritz** [comment]
I have the same issue. After a factory reset, the switch is off (in my case the smart plug v2) with the default restore mode (RESTORE_DEFAULT_ON) and logic.

**Comment by Roving-Ronin** [comment]
@Lordfritz 

Whilst I contribute a bunch of the official code, I find it simpler to run my own config for reasons like this.
If you want to have a look at running your own, try using this in your 'ESPHome Builder' individual device config for a v2 plug, just update the substituions to whatever your using the plug for:

```
substitutions:
  name: "gpo-dishwasher"
  friendly_name: "Dishwasher"
  device_description: "Athom Plug v2 - Phase C / GPO 1 - Dishwasher"
   # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  location: "Kitchen"
   # The phase in the home power supply, upon which this plug is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO 1 = Phase C, GPO 2 = Phase A, GPO 3 = Phase B)  
  power_circuit: "GPO 1"  

esphome:
  name_add_mac_suffix: false

esp8266:
  board: esp8285
  restore_from_flash: true

packages:
  remote_package:
    url: https://github.com/Roving-Ronin/myHomeAssistant/
    ref: main 
    files: [esphome/athom-smart-plug-v2.yaml]
    refresh: 3d
```
Sorts out the issue you raised, whilst using improved v3 webserver and adding sensors for energy that make sense (i.e. have a timescale associated with them, saving having to use utility_meter to do so in HomeAssistant).

If you like and want to customise, run your own version, then just copy my repo or the files (base config, components and associated files pulled by): https://github.com/Roving-Ronin/myHomeAssistant/blob/main/esphome/athom-smart-plug-v2.yaml
