### ISSUE TITLE
Upgrading to ESPHome 2024.10.0 prevents OTA from working

### ISSUE THREAD

**Issue by leonardospina** [athom-tech/athom-configs#101]
I have a few athom-4gang-switch devices around the house, and after the latest ESPHome update I installed this morning I cannot do OTA anymore, apparently the binary file is too large for OTA.
Updating form the ESPHome integration fails because of issues with name resolution (just ignore it), posting just to show the logs that show the size of the binary:

![image](https://github.com/user-attachments/assets/f400dfdb-b34d-406c-8d8f-aedaf4161e69)

but if I download the binary and upload it via the device's web UI I get this:

![image](https://github.com/user-attachments/assets/0e4bbb80-d888-4834-aa0e-f198a1d4807d)

**Comment by madberry** [comment]
Have you defined what esp is being used. I've seen this error come up a few times and after defining the esp OTA started to work again.

**Comment by leonardospina** [comment]
the board type is defined in the config in the original Athom's repo:

![image](https://github.com/user-attachments/assets/82fb578c-e5f6-435c-83a8-aee89757cbb9)

**Comment by madberry** [comment]
Have you tried to reboot the switch and then attempt the flash again?

**Comment by leonardospina** [comment]
No I haven't, I mean that's hardwired to the mains not really a quick thing... one thing I might try is resetting it to factory defaults and then flash it, but the strange thing is that it's not just one, all of them (same device type) have the same issue since I upgraded ESPHome

**Comment by leonardospina** [comment]
yeah very annoying... I'll try with one anyway and see if it works...

**Comment by Jannis87** [comment]
its an issue for me too. 

i think the binary is to big:
Flash: [=====     ]  53.9% (used 552101 bytes from 1023984 bytes)

**Comment by leonardospina** [comment]
yep same here, I have many devices and only the switches have that problem

**Comment by Jannis87** [comment]
> yep same here, I have many devices and only the switches have that problem

gzip -9 firmware.bin worked for me :). The compressed file can be uploaded via the web interface. Its a workaround, but at least my devices are up to date :)

**Comment by madberry** [comment]
I posted this issue to the esphome discord hopefully they will be able to pick it up.

**Comment by leonardospina** [comment]
Thanks for the hint I'll give it a try!

**Comment by leonardospina** [comment]
wow it worked! thanks @madberry

**Comment by cloudlena** [comment]
My solution is to have a very minimal configuration ready in ESPHome and always first flash that before I do any update. The minimal config results in a small firmware so that there is enough space on the device to then upload the actual update.

It's not nice, but it works 😅

**Comment by nirev** [comment]
@cloudlena can you share your minimal config? : )

**Comment by MaJerle** [comment]
> [@cloudlena](https://github.com/cloudlena) can you share your minimal config? : )

That's the strategy I can propose you for the product.

https://github.com/athom-tech/athom-configs/issues/122#issuecomment-3057866563

**Comment by nirev** [comment]
@MaJerle thank you! That worked perfectly : )

**Comment by cloudlena** [comment]
> [@cloudlena](https://github.com/cloudlena) can you share your minimal config? : )

```yaml
substitutions:
  name: athom-presence-sensor-abc123
  friendly_name: Athom Presence Sensor abc123

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: XXX

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp8266:
  board: esp8285
  restore_from_flash: true
ota:
  - platform: esphome
```
