### ISSUE TITLE
No Relay Power Monitoring EU Plug for ESPHome links to wrong yaml

### ISSUE THREAD

**Issue by Gunni** [athom-tech/athom-configs#105]
Hey,

The [No Relay Power Monitoring EU Plug for ESPHome](https://www.athom.tech/blank-1/no-relay-consumption-monitoring-eu-plug-for-esphome) links to [wrong yaml](https://github.com/athom-tech/athom-configs/blob/main/athom-smart-plug-v2.yaml).

You need a new yaml without the switch part. Or any of the power switch logic.

**Comment by Roving-Ronin** [comment]
@Gunni 
I'm still waiting for this plug to come out in the AU version, so can't test it myself. If you can...in your local device file, try adding:

```
select:
  - platform: template
    name: "Power On State"
    optimistic: true
    icon: "mdi:electric-switch"
    options:
      - Always Off
      - Always On
      - Restore Power Off State
    internal: true

switch:
  - platform: gpio
    name: "Switch"
    pin: GPIO15
    internal: true

```
then validate and flash it to your 'no relay' plug.  If you could confirm this does what your after, that would appear to be to remove the 'Power On State' and 'Switch' options from the devices webGUI / HA? 

Could you confirm this and also that no other errors are seen? The above should hide these, whilst the switch logic should just lie dormant in the background.

If this 'solves the issue' then we can see about making this into a subsitute option, so users of these plugs could add something like:

```
is_no_relay_plug: 'true'
```

to their substitutions section and have the existing Smart Plug v2 code work for them.
