### ISSUE TITLE
Missing .local in domain name for Athom devices

### ISSUE THREAD

**Issue by rmaeder** [athom-tech/athom-configs#111]
When I adopt an Athom Smart Plug V2 in ESPHome,
The link under the "VISIT" button uses the domain name athom-smart-plug-v2-ecXXX without .local appended; this does not work. Other devices, such as an Apollo Multisensor Mk1 use a domain name of apollo-msr-1-XXXX.local, which usually works.

When trying to update it, there is this error after the compilation, when it wants to upload the new configuration:

INFO resolving IP address of athom-smart-plug-v2-ecXXX

which fails for the same reason: the .local suffix is missing.

workaround: in the esphome config file for the device, add `domain: ".local"`:
```
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".local"
```
this should probably happen here: https://github.com/athom-tech/athom-configs/blob/main/athom-smart-plug-v2.yaml#L14

**Comment by Roving-Ronin** [comment]
@rmaeder It should be working fine with nothing in that substitution field, as it defaults to .local that way. If you unit isn't working then for YOUR devices, in each individual devices configuration file in ESPHome interface, you should add this:
```
substitutions:
  dns_domain: ".local"
```

For example your config for each device should look like:

```
substitutions:
  name: "gpo-clothes-dryer"
  friendly_name: "Clothes Dryer"
  device_description: "Athom Plug v2 - Phase B / GPO 3 - Clothes Dryer"
  location: "Laundry"
  dns_domain: ".local"

esphome:
  name_add_mac_suffix: false

esp8266:
  board: esp8285
  restore_from_flash: true

packages:
  remote_package:
    url: https://github.com/Roving-Ronin/myHomeAssistant/
    ref: main 
    files: [esphome/athom-smart-plug-v2.yaml]
    refresh: 5s # optional
```

(ignore the remote_package section, that points to my personal version for these plugs... yours should point to the https://github.com/athom-tech/athom-configs/blob/main/athom-without-relay-plug.yaml instead).
