### ISSUE TITLE
ESPHome Mini Firmware does not work on PG01v2 Plug

### ISSUE THREAD

**Issue by TheDK** [athom-tech/athom-configs#120]
Upload of Mini Firmware fails with: `Magic byte is not 0xE9`

To work around this I generated an mini firmware myself with ESPHome:

```
substitutions:
  device_name: "athom-pg01v2-miniflash"
  friendly_name: "Athom PG01v2 Mini Flash"
  project_name: "athom.pg01v2-miniflash"
  project_version: "1.0"

esphome:
  name: "${device_name}"
  name_add_mac_suffix: false
  friendly_name: "${friendly_name}"
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp8285

ota:
  - platform: esphome

logger:

web_server:
  port: 80

  ap:
    ssid: "AthomMiniFlash"
    password: "miniflash"
```

After flashing this to the device and connecting to the devices access point it was possible to flash the target firmware. YMMV.
