### ISSUE TITLE
switch button not working

### ISSUE THREAD

**Issue by vajonam** [athom-tech/athom-configs#52]
I am able to use the relay etc. via home assistant. I am unable get the physical button to trigger. 

Any help.I have 4 of these switches 3 of them work fine, the 4th stopped working sometime I am not sure when

is this a problem with physical switch? 

```
I am able to use the relay etc. via home assistant. I am unable get the physical button to trigger. 



esphome:
  name: ${name}
  comment: Storage room switch
  # friendly_name: ${friendly_name}

    
esp8266:
  board: esp8285
  restore_from_flash: true

preferences:
  flash_write_interval: 1min
  
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "/oZj6XGeElZWdjgDF7AIuGny9UyKfU34/N9BM2mFs="

ota:
  password: "134e0c035984dce36dd9c36081aa92"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smartswitch-09 Fallback Hotspot"
    password: "mFtZzOzgdv"

web_server:
  port: 80

captive_portal:


substitutions:
  name: smartswitch-09
  friendly_name: "Storage Room"
  project_name: "athom.sw01"
  project_version: "1.1"
  light_restore_mode: RESTORE_DEFAULT_OFF




binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

  # Touch Button
  - platform: gpio
    pin:
      inverted: true
      number: GPIO3
      mode:
        input: true
        pullup: true
    name: "${friendly_name} Button"
    disabled_by_default: True
    on_click:
      - logger.log: "Button clicked"
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - light.toggle: light1
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    disabled_by_default: true

button:
  - platform: factory_reset
    name: Restart with Factory Default Settings
    id: Reset

output:
  # Relay
  - platform: gpio
    pin: GPIO13
    id: relay1

  # Button LED (1.0 = Blue / 0.0 = Red)
  - platform: esp8266_pwm
    pin: GPIO14
    inverted: true
    id: button_led1

light:
  - platform: status_led
    name: "${friendly_name} Status LED"
    disabled_by_default: true
    pin:
      number: GPIO0
      inverted: true

  # Relay
  - platform: binary
    name: "${friendly_name} Light"
    id: light1
    output: relay1
    restore_mode: ${light_restore_mode}
    on_turn_on:
      - light.turn_on: led1
    on_turn_off:
      - light.turn_off: led1

  # Button LED
  - platform: monochromatic
    name: "${friendly_name} LED"
    disabled_by_default: true
    id: led1
    output: button_led1
    default_transition_length: 500ms

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      disabled_by_default: true
     
time:
  - platform: sntp
    id: my_time
```
