### ISSUE TITLE
lost total daily energy sensor in v2 plug 

### ISSUE THREAD

**Issue by rich-kettlewell** [athom-tech/athom-configs#82]
since updating to the latest esphome and reinstalling the latest athom-smart-plug-v2.yaml script, i’ve lost my total_daily_energy sensors.

**Comment by endyb66** [comment]
Right. The icon with the "24" number makes a lot of sense to me, the name "Total Energy Since Boot" however not so...

**Comment by Roving-Ronin** [comment]
Iirc the plugs have one reading that is supposed to be the 'daily' reading (but it's crap as if you reboot or flash it goes back to zero also) and another that is the Total sensor (kind of like a lifetime total).

IMHO best option was to ditch them all and move to using a custom component that gives a daily, yesterday, weekly, monthly and yearly sensor.

![image](https://github.com/user-attachments/assets/cd38330f-1d52-4432-8d47-b3edd9faf3ef)

**Comment by endyb66** [comment]
What's the custom component you are using?

**Comment by Roving-Ronin** [comment]
Have a look at the configuration that I run: 

v2 Plugs - https://github.com/Roving-Ronin/myHomeAssistant/blob/main/esphome/athom-smart-plug-v2.yaml

v3 Plugs - https://github.com/Roving-Ronin/myHomeAssistant/blob/main/esphome/athom-smart-plug-v3.yaml

Note that these configs call other yaml to then compile the 'full' yaml for each device, namely these plugs call:

Base Config, that applies the same set of standard sensors that ALL my esphome devices have:
  https://github.com/Roving-Ronin/myHomeAssistant/blob/main/esphome/common/base-configuration.yaml)

WiFi Config, sets up WiFi and adds the WiFi sensors I use:
  https://github.com/Roving-Ronin/myHomeAssistant/blob/main/esphome/common/network-wifi.yaml

Athom Plug config, allows having one file with all the athom plug specific settings in it, instead of seperate per version to maintain:
  https://github.com/Roving-Ronin/myHomeAssistant/blob/main/esphome/sensors/athom-power-plugs.yaml


In the athom plug config, I call the custom component (based off Dentra's, but expanded) using:

```
external_components:
  - source: github://roving-ronin/myhomeassistant/components@main
    refresh: 5s
```

Then from line 193 to 233 I call the sensors this adds: https://github.com/Roving-Ronin/myHomeAssistant/blob/cfbc444b6f77b36c1b5101c47481f049117d9b0b/esphome/sensors/athom-power-plugs.yaml#L193

I keep the existing Total Energy sensor (that roughly shows the lifetime kWh..or at least to some reflash stuffs it) at: https://github.com/Roving-Ronin/myHomeAssistant/blob/cfbc444b6f77b36c1b5101c47481f049117d9b0b/esphome/sensors/athom-power-plugs.yaml#L193

I also keep the existing Energy sensor (that I think you refer to as the 24hr one, but its useless as it resets when rebooted / flashed etc), but just change it to be 'internal', so it works within the ESP device and other sensors can call it if needed, but otherwise it isn't visible on the web GUI or published to HA: https://github.com/Roving-Ronin/myHomeAssistant/blob/cfbc444b6f77b36c1b5101c47481f049117d9b0b/esphome/sensors/athom-power-plugs.yaml#L185

I also use webserver v3 (instead of v2 your used to seeing) that allows sorting the order of sensors in the WebGUI (not HA) and if you click on a sensor it will show a graph of its data. 

Oh and in my Base config I also run an extra text sensor that allows defining the 'Power Circuit' (I have 3 phase and 3 different circuits for wall outlets in the house), that allows filtering ESP devices by the circuit they're on / turning devices off if they are on a certain phase etc.

I have to update my template for one thing currently, one I sort out this issue: https://github.com/athom-tech/athom-configs/discussions/87  pending that you can just apply it and make sure to update the selector in 'Power on State' to what you want.

Web Server GUI looks like:

![image](https://github.com/user-attachments/assets/c0f81e45-d4a0-41f7-8546-4e3bfea0b4ad)

Note: 

1. The new on_boot selector that athom added, even though I've changed to '2' (ALWAYS_ON) seems to come up with 'Power On State' is 'Always_Off' and the actual relay/swith turned off. You need to go to the WebGUI and turn on the relay (aka GPO Switch) and change the 'Power On State' to 'ALWAYS ON' (if thats your preference).

2.  The Week / Month / Year sensors will only start counting from the following Monday 0:00am / 1st of Month / 1st day of Year)

3. I've adding the mdi icon for the 'select' switch that has been recently added in athom repo, that MAY cause the core image to be rebuilt that then causes the periodical energy sensors to default to 0.0 kWh / NA. To avoid this I've just added the functionality into the custom component for it to store the value (in the ESP memory) and restore it by default. This is like adding 'globals' and then having the sensors write to them, but adding this functionality by default within the custom component. 

Could I ask that if you use this component, you let me know if this is working when booting/flashing in future. It should but feedback/confirmation appreciated.

Here's what the WebGUI should look like (yes the periodical energy sensors are NA....as adding that function (No.3 above) I had to take a hit for the team and reflash mine and see them reset to 0.0)

![image](https://github.com/user-attachments/assets/594e8cfc-e946-466e-9124-93012699ea7d)

**Comment by Roving-Ronin** [comment]
If you want to use the above, you can either FORK my repository and pull off your own repository, or else here's the yaml I use for a device to work in my ESPHome/HA and pull the code for the above.  

**_Please remember to update the substitutions to reflect the names / HA zone location / Power Circuit of your own device(s)._**

**Smart Plug v2**
```
substitutions:
  # Device name   
  name: "gpo-ups-study"
  # Device friendly name 
  friendly_name: "UPS - Study"
  # Description as appears in ESPHome & top of webserver page
  device_description: "Athom Plug v2 - Phase C / GPO 1 - Study PCs & Monitors"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc    
  location: "Study"
  # The phase in the home power supply, upon which this plug is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO 1 = Phase C, GPO 2 = Phase A, GPO 3 = Phase B)
  power_circuit: "TBC"

esphome:
  name_add_mac_suffix: false

esp8266:
  board: esp8285
  restore_from_flash: true

packages:
  remote_package:
    url: https://github.com/Roving-Ronin/myHomeAssistant/
    ref: main 
    files: [esphome/athom-smart-plug-v2.yaml]
    refresh: 5d # optional
```

**Smart Plug v3**
```
substitutions:
  # Device name
  name: "gpo-ups-network"
  # Device friendly name
  friendly_name: "UPS - Network Rack"
  # Description as appears in ESPHome & top of webserver page
  device_description: "Athom Plug v3 - Phase C / GPO 1 - Network Rack Devices"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  location: "Network Rack"
  # The phase in the home power supply, upon which this plug is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO1 = Phase C, GPO2 = Phase A, GPO3 = Phase B)
  power_circuit: "GPO 2"  

esphome:
  name_add_mac_suffix: false

packages:
  remote_package:
    url: https://github.com/Roving-Ronin/myHomeAssistant/
    ref: main 
    files: [esphome/athom-smart-plug-v3.yaml]
    refresh: 5d # optional
```
