### ISSUE TITLE
athom-rgbct-light: changed behaviour since updates

### ISSUE THREAD

**Issue by DoogeJ** [athom-tech/athom-configs#92]
I've recently updated the firmware on my 'athom-rgbct-light' (15W color bulb) lights to 2024.9.x (from something from 2023).
In this example I'm using one that has the name and friendly_name set to 'bedroom-light'

This changed the behavior in a few annoying ways:
- The device name in HA changed from 'light.bedroom_light_bedroom_light to light.bedroom_light_rgbcct_bulb, breaking all automation and cards
- The default behavior on power loss changed so that it now stays off (it goes on for a split second, then turns off once it connects); this stops us from using the normal light switches in the house
- I seem to no longer be able to set the light to a specified brightness in the automations in HA. I can still brightness_increase and brightness_decrease, but not set a specific %

I think the reason is the changes in e1b4785afa538e04f53a399765187848fe1f3db9 but I'm not sure about all technical details.

Contents of my bedroom-light.yaml ESPHome configuration for this example:
```yaml
substitutions:
  name: bedroom-light
  friendly_name: bedroom-light
packages:
  athom.rgbct-light: github://athom-tech/athom-configs/athom-rgbct-light.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: *snip*


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
